# -*- coding: utf-8 -*-
# Part of Flous Flow. See LICENSE file for full copyright and licensing details.
"""Traceability + protection: generated combo items are managed by their source."""

from odoo import fields, models
from odoo.exceptions import ValidationError
from odoo.tools.translate import _

PROTECTED_MANAGED_FIELDS = ('combo_id', 'product_id', 'ff_variant_source_id')


class ProductComboItem(models.Model):
    _inherit = 'product.combo.item'

    ff_variant_source_id = fields.Many2one(
        comodel_name='ff.variant.source', string="Variant Source", index=True,
        ondelete='cascade',
        help="Set when this combo item was generated by a Smart Variant Source. "
             "Empty for manual items, which are never touched by the sync engine.",
    )

    def write(self, vals):
        managed = self.filtered('ff_variant_source_id')
        if managed and set(vals.keys()) & set(PROTECTED_MANAGED_FIELDS):
            # Identity of a generated item can only change via its source sync.
            vals = {k: v for k, v in vals.items() if k not in PROTECTED_MANAGED_FIELDS}
            self = self - managed
        return super(ProductComboItem, self).write(vals)

    def unlink(self):
        combos = self.mapped('combo_id')
        res = super().unlink()
        # Re-validate affected combos after manual item removal (constraint
        # does not fire on comodel unlink).
        for combo in combos:
            if combo.exists() and not combo.combo_item_ids and not combo.ff_variant_source_ids:
                raise ValidationError(_(
                    "A combo choice must contain at least 1 product."
                ))
        return res
